#define Help_Search_Window 20
#define Help_TOC_Window 21
#define Manage_Window_Layouts_Dialog 24
#define Messages_Window 26
#define Help_Glossary_Window 18
#define Help_Index_Window 19
#define Index_Results_Window 23
#define Manage_Windows_Dialog 25
#define Help_Favorites_Window 17
#define Recent_Files_Dialog 34
#define Start_Page 40
#define Options_Dialog 53
#define Recent_Projects_Dialog 59
#define Alignment_Tool 83
#define File_Map_Window_Pane 84
#define Start_Alignment_Wizard 82
#define Conflict_with_Translation_Memory_Dialog 63
#define across_Translation_Memory_Settings_Dialog 2
#define Current_Translation_Memory_Provider_Dialog 3
#define Select_Translation_Memory_Dialog 4
#define Select_Database_Dialog 5
#define Crash 85
