#define Columns_Dialog 2
#define Help_Favorites_Window 5
#define Help_Glossary_Window 6
#define Help_Index_Window 7
#define Help_Search_Window 8
#define Help_TOC_Window 9
#define Index_Results_Window 10
#define Feedback_Admin 11
#define Messages_Window 12
#define New_Local_Target_Dialog 13
#define New_Updates_Available_Dialog 14
#define Options_Dialog 15
#define Comments_Window 16
#define Recent_Files_Dialog 17
#define Registered_Users_Window 18
#define Search_Phrases_Window 19
#define Search_Phrases_With_No_Results_Window 20
#define Start_Page 21
#define Synonyms_Editor 23
#define Topics_Window 24
#define Color_Picker_Dialog 26
#define Manage_Window_Layouts_Dialog 27
#define Manage_Windows_Dialog 28
#define Topic_View_Window 33
#define Print_Preview_Dialog 34
#define Properties_Dialog_Searches_Without_Results 35
#define Properties_Dialog_Used_Search_Phrases 37
#define CSH_Help_Calls_Window 39
#define Date_Filter_Dialog 40
#define Browser_Statistics_Window 42
#define Operating_System_Statistics_Window 43
#define Add_Administrator_Dialog 44
#define Administrator_Properties_Dialog 45
#define Chart_Options_Dialog 46
#define Edit_Comment_Dialog 47
#define Customize_Email_Message_Dialog 48
#define New_Task_Dialog 49
#define Date_Filter_Dialog_Manifest 50
#define Edit_Task_Dialog 51