#define Help_Search_Window 20
#define Help_TOC_Window 21
#define Manage_Window_Layouts_Dialog 24
#define Messages_Window 26
#define Help_Glossary_Window 18
#define Help_Index_Window 19
#define Index_Results_Window 23
#define Manage_Windows_Dialog 25
#define Options_Dialog_General_Tab 29
#define Help_Favorites_Window 17
#define New_Updates_Available_Dialog 28
#define File_List_Window 13
#define Recent_Files_Dialog 34
#define Properties_Dialog_Generic_Basic_Tab 32
#define Start_Page 40
#define Start_New_Project_Wizard_Select_Language_Page 37
#define Start_New_Project_Wizard_Ready_Create_Project_Page 39
#define Start_New_Project_Wizard_Enter_Project_Name_Folder_Page 38
#define Connect_to_SQL_Server_Dialog 3
#define Current_Translation_Memory_Provider_Dialog 8
#define Export_Translated_Project_Dialog 12
#define New_Database_Dialog 27
#define Project_Editor 30
#define Properties_Dialog_Generic_Translation_Tab 31
#define Select_Translation_Memory_Dialog 35
#define Start_New_Project_Wizard_Source_Project_Page 36
#define Select_Database_Dialog 50
#define Options_Dialog 53
#define Properties_Dialog_Generic 54
#define across_Translation_Memory_Settings_Dialog 56
#define Recent_Projects_Dialog 59
#define Ignored_Words_Dialog 60
#define Start_New_Project_Wizard 61
#define Conflict_with_Translation_Memory_Dialog 63
#define Backups_Window 64
#define Conflicts_with_Translation_Memory_Dialog 65
#define Export_to_TMX_Dialog 66
#define Import_TMX_File_Dialog 67
#define Options_Dialog_Suggestions_Tab 73
#define Start_Alignment_Wizard 82
#define Alignment_Tool 83
#define File_Map_Window_Pane 84
#define Database_Version_Conflict_Dialog 85
#define Translation_Memory_Editor 86
#define Statistics_Browser 97
#define Termbase_Window_Pane 89
#define Manage_Termbases_Dialog 90
#define Enter_New_Termbase_Name_Dialog 91
#define Add_Term_to_Termbase_Dialog_Termbase_Editor 92
#define Termbase_Editor 93
#define Export_to_TBX_Dialog 94
#define Import_TBX_File_Dialog 95
#define Enter_External_Reference_Dialog 103
#define Enter_Image_Reference_Dialog 104
#define Color_Picker_Dialog 105
#define Language_Set_Dialog 108
#define Termbase_Concept_Dialog 109
#define Create_New_Project_Bundle_Wizard 110
#define Add_Batch_Terms_to_Termbase_Dialog 111
#define Add_Term_to_Termbase_Dialog_Suggestions_Window 112
#define Translation_Editor 113
#define Find_in_Files_Window 116
#define Find_Results_1_Window 117
#define Find_Results_2_Window 118
#define Save_for_Review_Dialog 119
#define Getting_Started_Wizard 120
#define Concordance_Reg_Expression 121
#define Segmentation_Rules_Spaces 122
#define Segmentation_Rule_Editor 123
#define Concordance_Search_Window_Pane 124
#define Updating_Segments_With_Context_Matches 125
#define Updating_Translations_With_Identical_Source 126
#define Character_Dialog 127
#define Log_File_Viewer 128
#define Crash 129
#define Create_Bundle_Dialog 130
#define File_Filters_Dialog 131
#define Attribute_Restriction_Dialog 132
#define Add_Project_Files_Wizard 133
#define New_Local_Translation_Memory_Database_Dialog 134
#define New_Database_Dialog_TM 135
#define New_Local_Termbase_Database_Dialog 136
#define New_Database_Dialog_TB 137
#define Machine_Translation_Providers_Dialog 138
#define Quality_Assurance_Dialog 139
#define Metadata_Viewer_Dialog 140
#define Metadata_Filter_Dialog 141
#define TM_Cleanup_Find_and_Replace_Dialog 142
#define TM_Cleanup_Delete_Dialog 143
#define TM_Cleanup_Duplicates_Dialog 144
