#define Welcome 1
#define Current_Frame_Editor 2
#define Frame_Properties_Dialog 3
#define Manage_Window_Layouts_Dialog 4
#define Messages_Window 5
#define Object_Properties_Dialog 6
#define Help_Favorites_Window 8
#define Help_Glossary_Window 9
#define Help_Index_Window 10
#define Help_Search_Window 11
#define Help_TOC_Window 12
#define Index_Results_Window 13
#define Manage_Windows_Dialog 14
#define New_Updates_Available_Dialog 15
#define Start_Page 16
#define Project_Movies_Window 17
#define Frames_Window 18
#define Timeline_Window 19
#define Getting_Started_Wizard 20
#define Start_New_Collection_Wizard 21
#define Movie_Properties_Dialog 22
#define Project_Editor 23
#define Palettes_Window 24
#define MadCap_Movie_Player 25
#define Add_Mimic_Movie_Dialog 26
#define Section_Title_Dialog 27
#define Select_Window 28
#define New_Palette_Dialog 29
#define Rename_Movie_Dialog 30
#define Pick_System_Sound_Dialog 32
#define Manage_Movie_Sound_Library_Dialog 33
#define Options_Dialog 34
#define Select_Shape_Style_Dialog 35
#define Recording_Options_Dialog 36
#define Dynamic_Help_Window 38
#define Accept_Recorded_Movie_Dialog 39
#define Color_Picker_Dialog 40
#define Bubble_Properties_Dialog 42
#define Cursor_Properties_Dialog 43
#define Oval_Properties_Dialog 44
#define Polygon_Properties_Dialog 45
#define Polyline_Properties_Dialog 46
#define Rectangle_Properties_Dialog 47
#define Typing_Box_Properties_Dialog 48
#define Button_Properties_Dialog 49
#define Input_Box_Properties_Dialog 50
#define Rollover_Caption_Properties_Dialog 51
#define Link_Browser_Window 52
#define Skin_Editor 53
#define Import_Movie_Dialog 54
#define Pick_Skin_Dialog 55
#define Save_Skin_Dialog 56
#define Toolbar_JavaScript_Dialog 57
#define Publish_Movie_Dialog 58
#define Log_On_As_Dialog 59
#define Publishing_Log_Dialog 60
#define Image_Properties_Dialog 61
#define Effect_Properties_Dialog 62
#define Failure_Caption_Properties_Dialog 63
#define Hint_Caption_Properties_Dialog 64
#define Ignored_Words_Dialog 65
#define Language_Skin_Editor 66
#define Language_Skins_Dialog 67
#define Open_Dictionary_Dialog 68
#define Record_Dialog 69
#define Select_Template_Language_Skin_Dialog 70
#define Sound_Editor 71
#define Spell_Check_Window 72
#define Success_Caption_Properties_Dialog 73
#define Dictionary_Editor 74
#define Adjust_Volume_Dialog 75
#define Insert_Silence_Dialog 76
#define Variables_Dialog 77
#define Trajectory_Drawing_Dialog 78
#define Adobe_AIR_Options_Dialog 79
#define Recent_Files_Dialog 84
#define Recent_Collections_Dialog 85
#define Frame_Libraries_Window_Pane 88
#define Master_Frames_Window_Pane 89
#define New_Target_Dialog 90
#define New_Library_Dialog 91
#define Master_Frame_Properties_Dialog 92
#define Silverlight_Options_Dialog 93
#define Build_Targets_Dialog 94
#define Define_Font_Set_Dialog 95
#define Font_Family_Picker_Dialog 96
#define Pick_Font_List_Dialog 97
#define Arrow_Properties_Dialog 98
#define Loop_Properties_Dialog 99
#define Import_PowerPoint_Wizard 100
#define Import_PowerPoint_Wizard2 101
#define Pick_Master_Frames_Dialog 102
#define Grid_Options_Dialog 103
#define Add_Sound_to_Frame_Dialog 104
#define Flash_Options_Dialog 105
#define Embedded_Skin_Options_Dialog 106
#define New_Dialog 107
#define HTML5_Options_Dialog 108
#define Crash 109
