#define Manage_Window_Layouts_Dialog 11
#define Messages_Window 13
#define Help_Favorites_Window 5
#define Help_Glossary_Window 6
#define Help_Index_Window 7
#define Help_Search_Window 8
#define Help_TOC_Window 9
#define Index_Results_Window 10
#define Manage_Windows_Dialog 12
#define New_Updates_Available_Dialog 14
#define Start_Page 15
#define Frames_Window_Pane_MovieSync 3
#define Current_Frame_Editor 19
#define Recent_Files_Dialog 22
#define Select_Old_Movie_Dialog 25
#define Open_Mimic_Projects_Dialog 26
#define Properties_Window_Pane_MovieSync 27
#define Old_Movie_Version_Window 28
#define Options_Dialog 17
#define Grid_Options_Dialog 29
#define Crash 30
